language: php

php:
  - 7.0
  - 7.1
before_script:
  - sudo apt-get install unzip
  - wget https://github.com/davidmgilo/timetables/archive/master.zip -O ~/timetables-master.zip
  - unzip ~/timetables-master.zip
  - wget https://github.com/acacha/l5-repository/archive/master.zip -O ~/l5-repository-master.zip
  - unzip ~/l5-repository-master.zip
  - cp studio.travis.json studio.json
  - composer update
  - composer install --prefer-source --no-interaction --dev
  - cp .env.example .env
  - touch database/database.sqlite
  - php artisan migrate && php artisan passport:install

script: phpunit --coverage-text --coverage-clover=coverage.clover


after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi