language: php

php:
  - 7.0
  - 7.1
before_script:
  - wget https://github.com/davidmgilo/timetables/archive/master.zip
  - tar -xvf timetables-master.zip
  - wget https://github.com/acacha/l5-repository/archive/master.zip
  - tar -xvf l5-repository-master.zip
  - composer install --prefer-source --no-interaction --dev
  - cp .env.testing .env
  - touch database/database.sqlite
  - php artisan migrate && php artisan passport:install

script: phpunit --coverage-text --coverage-clover=coverage.clover


after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi